name: Bash Script
on: workflow_dispatch
jobs:
  bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v3
      - name: Run Bash Script
        run: bash ./.github/workflows/testing.sh
    
